project:
  type: website
  output-dir: docs
  
website:
  title: "Undergraduate Forestry Data Science"
  favicon: images/placeholder.png
  navbar:
    logo: images/placeholder.png
    left:
      - icon: github
      #  href: #https://github.com/yourusername
      #- icon: #twitter
      #  href: #https://twitter.com/yourusername
    right:
      - text: "Home"
        href: index.qmd
      - text: "People"
        href: people.qmd
      - text: "Showcase Projects"
        href: previousProjects.qmd
      - text: "Application Information"
        href: application.qmd
    search: true

format:
  html:
    page-layout: full
    css: styles.css
    toc: true
    toc-location: right
    toc-title: "On this page"
    
    toc-collapse: true
    toc-depth: 3
    toc-expand: true

resources: 
  - CNAME